let _id = 0
const item = (name, price) => ({ id: ++_id, name, price, image: null, available: true })

export const menuData = [
  {
    id: 'fatias',
    name: 'Fatias de Bolo',
    emoji: '🎂',
    items: [
      item('Abacaxi com Coco', 18),
      item('Abacaxi com Doce de Leite', 18),
      item('Bolo Pudim com Brigadeiro Branco', 20),
      item('Bolo Pudim com Doce de Leite', 20),
      item('Choco Ninho', 18),
      item('Chocolatudo', 18),
      item('Doce de Leite com Ameixa', 18),
      item('Doce de Leite com Ninho', 18),
      item('Limão', 16),
      item('Maracujá', 16),
      item('Maracujá com Chocolate', 18),
      item('Mousse de Chocolate', 18),
      item('Ninho com Geleia de Morango', 20),
      item('Ninho com Morangos Frescos', 22),
      item('Ninho com Nutella', 22),
      item('Olho de Sogra', 18),
      item('Paçoca', 16),
      item('Prestígio', 18),
      item('Romeu e Julieta', 18),
      item('Floresta Negra', 20),
      item('Ninho', 18),
      item('Brigadeiro', 16),
      item('Frutas', 18),
      item('Alpino', 20),
      item('Surpresa de Uva', 20),
    ],
  },
  {
    id: 'bolos-inteiros',
    name: 'Bolos Inteiros',
    emoji: '🎉',
    items: [
      item('Bolo de Maracujá com Chocolate', 90),
      item('Bolo Red Velvet', 110),
      item('Bolo Ninho com Nutella', 120),
      item('Bolo Prestígio', 95),
      item('Bolo Brigadeiro', 85),
      item('Bolo Maracujá', 80),
      item('Bolo Limão', 80),
      item('Surpresa de Uva', 95),
      item('Surpresa de Morango', 100),
    ],
  },
  {
    id: 'delicias-pote',
    name: 'Delícias no Pote',
    emoji: '🍮',
    items: [
      item('Red Velvet', 16),
      item('Banoffee Cookies', 18),
    ],
  },
  {
    id: 'palha-italiana',
    name: 'Palha Italiana',
    emoji: '🍫',
    items: [
      item('Gotas de Chocolate Recheado com Nutella', 12),
      item('Nutella', 12),
      item('Brigadeiro', 10),
    ],
  },
  {
    id: 'pao-de-mel',
    name: 'Pão de Mel',
    emoji: '🍞',
    items: [
      item('Maracujá', 9),
      item('Prestígio', 9),
      item('Doce de Leite', 9),
      item('Ninho com Nutella', 11),
      item('Ninho', 9),
      item('Brigadeiro', 9),
    ],
  },
  {
    id: 'cones',
    name: 'Cones',
    emoji: '🍦',
    items: [
      item('Maracujá', 12),
      item('Prestígio', 12),
      item('Doce de Leite', 12),
      item('Ninho com Nutella', 14),
      item('Ninho', 12),
      item('Brigadeiro', 12),
      item('Paçoca', 12),
    ],
  },
  {
    id: 'bebidas',
    name: 'Bebidas',
    emoji: '🥤',
    items: [
      item('Gatorade 500ml', 10),
      item('Monster Mango Loco 473ml', 12),
      item('Monster Pipeline Punch 473ml', 12),
      item('Monster Energy Original 473ml', 12),
      item('Heineken 473ml', 10),
      item('Guaraná Antarctica lata 350ml', 6),
      item('Sprite lata 350ml', 6),
      item('Coca-Cola lata 350ml', 6),
      item('Coca-Cola Zero lata 350ml', 6),
      item('Fanta Uva lata 350ml', 6),
      item('Fanta Laranja lata 350ml', 6),
      item('Coca-Cola 200ml', 4),
      item('Guaraná Antarctica 200ml', 4),
      item('Água Crystal sem gás 500ml', 4),
      item('Água com gás 500ml', 5),
      item('Surfrutos Maracujá 500ml', 8),
      item('Surfrutos Laranja 500ml', 8),
      item('Surfrutos Goiaba 500ml', 8),
      item('Surfrutos Caju 500ml', 8),
    ],
  },
]
